# Generated by Django 5.0.2 on 2025-06-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_like_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='time_update',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
