# Generated by Django 5.0.2 on 2025-06-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_like_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='time_update',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
