# Generated by Django 5.0.2 on 2025-06-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_like_time_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_status',
            field=models.CharField(choices=[(1, 'like'), (0, 'none')], default=None),
        ),
    ]
