# Generated by Django 5.0.2 on 2025-06-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_like_like_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_status',
            field=models.CharField(choices=[('like', 1), ('none', 0)], default=None),
        ),
    ]
