# Generated by Django 5.0.2 on 2025-06-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_like_like_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
